services:
  - type: web
    name: cv-builder-app
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_d1n8XQarhOIw@ep-old-night-aturr3q4.c-9.us-east-1.aws.neon.tech/neondb?sslmode=require
